### ISSUE TITLE
Question: Why use `noh` over `let @\ = ""` to clear last search?

### ISSUE THREAD

**Issue by xaviervalarino** [gf3/dotfiles#28]
I was searching for how to clear search and not have the last pattern reappear when sourcing a file.
I came across your config, and was wondering: is a particular reason why you decided to use the `noh` command over `let @\ = ""`?

https://github.com/gf3/dotfiles/blob/2b1e85805fa1a0514373defdd9b9f80ae26579f1/.config/nvim/init.vim#L159-L162

**Comment by gf3** [comment]
@xaviervalarino `:noh` is preferred because it doesn't clear the search register. often i will search for something and then no longer want it highlighted as i make changes, but later i will want to search for it again. when using `:noh` you can simply hit `n` or `N` (or any of the other search motions). whereas if you clear the register you need to make a brand-new search with the original term

that's just one example, i find it handy to keep the term in the register and just disable highlighting

**Comment by xaviervalarino** [comment]
Thank you for the thoughtful and thorough answer.
